website/website/__init__.py
from flask import Flask #nosso app
from flask import request #recebe informações do usuário

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = '12345'

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    return app

website/website/auth.py
from flask import Blueprint, request, render_template
from functions import *
from placas import *
from flask import redirect, url_for

auth = Blueprint('auth', __name__)

potTotal = None #teste1
areaTelhado = None
areaPlaca = None
voltagem = None
amperagem = None
potZerarLuz = None
valortotal = None
alturatelhado = None
comprimentotelhado = None
consumomensal = None
valortotal = None
qtddias = None
qtdPlacasNec = None
voltagemNec = None
amperagemNec = None
potTotalNec = None
geracaoMensalNec = None
valortotalNec = None
potInv = None
estadoTela1 = None
estadoTela2 = None
estadoTela3 = None
estadoTela4 = None


def ControlarEstadosPagina(nmrPagina):
     global estadoTela1 
     global estadoTela2 
     global estadoTela3 
     global estadoTela4 
     if nmrPagina == 1:
          estadoTela1 = 'inline'
          estadoTela2 = 'none'
          estadoTela3 = 'none'
          estadoTela4 = 'none'
     elif nmrPagina == 2:
               estadoTela1 = 'none'
               estadoTela2 = 'inline'
               estadoTela3 = 'none'
               estadoTela4 = 'none'
     elif nmrPagina == 3:
               estadoTela1 = 'none'
               estadoTela2 = 'none'
               estadoTela3 = 'inline'
               estadoTela4 = 'none' 
     elif nmrPagina == 4:
               estadoTela1 = 'none'
               estadoTela2 = 'none'
               estadoTela3 = 'none'
               estadoTela4 = 'inline'          
               
@auth.route('send_data', methods=['POST'])
def send_data():
    global alturatelhado
    global comprimentotelhado
    global consumomensal
    global valortotal
    global qtddias
    global potTotal
    global areaTelhado
    global areaPlaca
    global qtdPlacas
    global potTotal
    global voltagem
    global amperagem
    global potZerarLuz
    global geracaoMensal
    global valortotal
    global qtdPlacasNec
    global voltagemNec
    global amperagemNec
    global potTotalNec
    global geracaoMensalNec
    global valortotalNec


    ControlarEstadosPagina(2)


    #2)Agora deve-se solicitar ao usuário os dados de sua instalação para que o sistema possa sugerir algumas possibilidades ao usuário
    #INPUTS
    alturatelhado = float(request.form['altura-telhado'])
    comprimentotelhado = float(request.form['comprimento-telhado'])
    consumomensal = float(request.form['consumo-mensal'])
    valortotal = float(request.form['valor-total'])
    qtddias = int(request.form['qtd-dias'])
    
    #calculos
    areaTelhado = calcularArea(alturatelhado, comprimentotelhado)
    areaPlaca = calcularAreaPlaca(CANADIANSOLAR.alturaPlaca, CANADIANSOLAR.larguraPlaca)
    qtdPlacas = divisaoAtAp(areaTelhado, areaPlaca)
    potTotal = multiplicacaoQtdPlacaPotPlaca(qtdPlacas, CANADIANSOLAR.potenciaPainel)
    voltagem = multiplicacaoQtdPlacaVoltagem(qtdPlacas, CANADIANSOLAR.voltagemPainel)
    amperagem = multiplicacaoQtdPlacaAmperagem(qtdPlacas, CANADIANSOLAR.correntePainel)
    potZerarLuz = divisaoConsumomensalQtddias(consumomensal, qtddias)
    geracaoMensal = calculoGeracaoMensal(potTotal, qtddias)
    valortotal = calculoValortotal(geracaoMensal)
    
    #cálculos do 2º quadro
    qtdPlacasNec = divisaoAtApNec(consumomensal, geracaoMensal)
    voltagemNec = multiplicacaoQtdPlacaVoltagemNec(qtdPlacasNec, CANADIANSOLAR.voltagemPainel)
    amperagemNec = multiplicacaoQtdPlacaAmperagemNec(qtdPlacasNec, CANADIANSOLAR.correntePainel)
    potTotalNec = multiplicacaoQtdPlacaPotPlacaNec(qtdPlacasNec, CANADIANSOLAR.potenciaPainel)
    geracaoMensalNec = calculoGeracaoMensalNec(potTotalNec, qtddias)
    valortotalNec = calculoValortotalNec(geracaoMensalNec)

    alturaPlaca=CANADIANSOLAR.alturaPlaca
    larguraPlaca=CANADIANSOLAR.larguraPlaca
    qtdPlacas=qtdPlacas

    return render_template ('base.html', areaTelhado=areaTelhado, areaPlaca=areaPlaca, alturaPlaca=CANADIANSOLAR.alturaPlaca, 
    larguraPlaca=CANADIANSOLAR.larguraPlaca, qtdPlacas=qtdPlacas, potTotal=multiplicacaoQtdPlacaPotPlaca(qtdPlacas, CANADIANSOLAR.potenciaPainel), 
    voltagem=voltagem, amperagem=amperagem, potZerarLuz=potZerarLuz, geracaoMensal=calculoGeracaoMensal(potTotal, qtddias), valortotal=valortotal, 
    voltagemNec=voltagemNec, amperagemNec=amperagemNec, potTotalNec=potTotalNec, qtdPlacasNec=qtdPlacasNec, geracaoMensalNec=calculoGeracaoMensalNec(potTotalNec, qtddias), 
    valortotalNec = calculoValortotalNec(geracaoMensalNec),estadoTela1 = estadoTela1,estadoTela2 = estadoTela2,estadoTela3 = estadoTela3,estadoTela4 = estadoTela4)


@auth.route('send_data2', methods=['post'])
def send_data2():
   global quadro
   quadro = request.form.get('quadro')
   ControlarEstadosPagina(3)
   
   return render_template('base.html', quadro=quadro, areaTelhado=areaTelhado, areaPlaca=areaPlaca, alturaPlaca=CANADIANSOLAR.alturaPlaca, 
    larguraPlaca=CANADIANSOLAR.larguraPlaca, qtdPlacas=qtdPlacas, potTotal=multiplicacaoQtdPlacaPotPlaca(qtdPlacas, CANADIANSOLAR.potenciaPainel), 
    voltagem=voltagem, amperagem=amperagem, potZerarLuz=potZerarLuz, geracaoMensal=calculoGeracaoMensal(potTotal, qtddias), valortotal=valortotal, 
    voltagemNec=voltagemNec, amperagemNec=amperagemNec, potTotalNec=potTotalNec, qtdPlacasNec=qtdPlacasNec, geracaoMensalNec=calculoGeracaoMensalNec(potTotalNec, qtddias), 
    valortotalNec = calculoValortotalNec(geracaoMensalNec),estadoTela1 = estadoTela1,estadoTela2 = estadoTela2,estadoTela3 = estadoTela3,estadoTela4 = estadoTela4)



@auth.route('send_data3', methods=['POST'])
def send_data3():    
    global alturatelhado
    global comprimentotelhado
    global consumomensal
    global valortotal
    global qtddias
    global potTotal
    global areaTelhado
    global areaPlaca
    global qtdPlacas
    global potTotal
    global voltagem
    global amperagem
    global potZerarLuz
    global geracaoMensal
    global valortotal
    global qtdPlacasNec
    global voltagemNec
    global amperagemNec
    global potTotalNec
    global geracaoMensalNec
    global valortotalNec
    global potInv
    global quadro
    global prodEletrica
    global payback
    global producao
    global potencia


    potTotal = multiplicacaoQtdPlacaPotPlaca(qtdPlacas, CANADIANSOLAR.potenciaPainel)
    potInv = float(request.form['potInv'])
    voltagemInv = float(request.form['voltagemInv'])
    amperagemInv = float(request.form['amperagemInv'])

    if quadro == '1':
     potTotalLoc = potTotal
     voltagemLoc = voltagem
     amperagemLoc = amperagem
     valortotalLoc = valortotal
    else:           
     potTotalLoc =  potTotalNec
     voltagemLoc = voltagemNec
     amperagemLoc =  amperagemNec
     valortotalLoc = valortotalNec
   
    
    nmenor = Inversores(potTotalLoc, voltagemLoc, amperagemLoc, potInv, voltagemInv, amperagemInv)
    prodEletrica = CalculoProdEletrica(potTotalLoc)
    producao = prodEletrica * 12 * 0.70
    
    if prodEletrica <= 30:
         taxa = '20,40'
    elif prodEletrica > 30 and prodEletrica <= 50:
         taxa = '34,00'
    elif prodEletrica > 50:
         taxa = '68,00'
    
    payback = valortotalLoc / producao
    ControlarEstadosPagina(4)

    return render_template('base.html', nmenor=round(nmenor), prodEletrica=prodEletrica, taxa=taxa, payback=round(payback, 1), areaTelhado=areaTelhado, areaPlaca=areaPlaca, alturaPlaca=CANADIANSOLAR.alturaPlaca, 
    larguraPlaca=CANADIANSOLAR.larguraPlaca, qtdPlacas=qtdPlacas, potTotal=multiplicacaoQtdPlacaPotPlaca(qtdPlacas, CANADIANSOLAR.potenciaPainel), 
    voltagem=voltagem, amperagem=amperagem, potZerarLuz=potZerarLuz, geracaoMensal=calculoGeracaoMensal(potTotal, qtddias), valortotal=valortotal, 
    voltagemNec=voltagemNec, amperagemNec=amperagemNec, potTotalNec=potTotalNec, qtdPlacasNec=qtdPlacasNec, geracaoMensalNec=calculoGeracaoMensalNec(potTotalNec, qtddias), 
    valortotalNec = calculoValortotalNec(geracaoMensalNec),estadoTela1 = estadoTela1,estadoTela2 = estadoTela2,estadoTela3 = estadoTela3,estadoTela4 = estadoTela4)


website/website/views.py
from flask import Blueprint, render_template, request
views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("home.html", estadoTela1 = "inline",estadoTela2 ="none",estadoTela3 ="none",estadoTela4 ="none")

@views.route('sobre.html')
def sobre():
   return render_template('sobre.html')

website/website/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, inital-scale-1" />
    <link rel="stylesheet" href="../static/css/master.css" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    />
    <link rel="icon" type="image/svg" href="../static/images/logotipo2.svg" />
    <title>Simulador de capacidade de geração de energia solar</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm fixed-top">
      <!-- logo do IFF -->
      <!--
  <a target="_blank" class="navbar-brand" href="https://portal1.iff.edu.br/nossos-campi/bom-jesus-do-itabapoana">
    <img width="25%" src="website\static\images\ifflogo.png" alt="">
  </a>
-->
      <!-- items da barra de navegação -->
      <div
        class="p-3 collapse navbar-collapse flex-row-reverse bg-warning"
        id="collapsibleNavbar"
      >
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" href="/"><b>início</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="sobre.html">sobre</a>
          </li>
        </ul>
      </div>
    </nav>

    <br /><br /><br /><br />

    <div class="container p-5 text-center">
      <h1>Simulador de capacidade de geração de energia solar</h1>
      <hr/ class="l">
    </div>

    <!--Agora deve-se solicitar ao usuário os dados de sua instalação para que o sistema possa sugerir algumas possibilidades ao usuário-->
    <div class="container p-3 text-center" style="display:{{ estadoTela1 }}">
      <h4>Dados da instalação</h4>
      <br />

      <form
        action="{{ url_for('auth.send_data') + '#secao2' }}"
        id="entrada-dados"
        action="index.html"
        method="post"
      >
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label for="">Altura do telhado disponível (em metros):</label>
              <input
                type="text"
                class="form-control"
                name="altura-telhado"
                value=""
              />
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group">
              <label for=""
                >Comprimento do telhado disponível (em metros):</label
              >
              <input
                type="text"
                class="form-control"
                name="comprimento-telhado"
                value=""
              />
            </div>
          </div>
        </div>

        <br /><br />

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <label for="">Consumo mensal de KW/H na conta de luz:</label>
              <input
                type="text"
                class="form-control"
                name="consumo-mensal"
                value=""
              />
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
              <label for="">Valor total da conta de luz:</label>
              <input
                type="text"
                class="form-control"
                name="valor-total"
                value=""
              />
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
              <label for=""
                >Período de leitura na conta de luz (em dias):</label
              >
              <input
                type="text"
                class="form-control"
                name="qtd-dias"
                value=""
              />
            </div>
          </div>
        </div>

        <br />
        <div class="col-md-12">
          <a href="auth.send_data#secao2"
            ><input type="submit" class="btn btn-lg" name="" value="Calcular"
          /></a>
        </div>
      </form>
    </div>

    <div
      class="jumbotron text-center resultado"
      action="{{ url_for('auth.send_data') }}"
      style="display:{{ estadoTela2 }}"
    >
      <div class="container" name="calculando" id="secao2" >
        <h2>Quase lá! Agora escolha o quadro ideal para seu inversor:</h2>

        <div class="container">
          <form
            action="{{ url_for('auth.send_data2') + '#secao3'  }}"
            id="entrada-dados"
            action="{{ url_for('auth.send_data2') }}"
            method="post"
          >
            <div class="row r_quadros">
              <div class="col-md">
                <br />
                <input type="radio" name="quadro" id="1" value="1" />
                <label for="1" class="l_quadro">
                  <div class="p-2 border bg-light quadros">
                    <h2 class="p-2">Quadro 1</h2>
                    <p class="text-left" style="margin-left: 20px">
                      Área de cada placa: {{ areaPlaca }}m²
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Área total do telhado: {{ areaTelhado }}m²
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Quantidade de placas que
                      <span style="font-weight: bold">podem</span> ser
                      instaladas: {{ qtdPlacas }} placas
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Potência total em Watts: {{ potTotal }}W
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Potência total em Volts: {{ voltagem }}V
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Potência total em Amperes: {{ amperagem }}A
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Geração mensal: {{ geracaoMensal }}W
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Valor total de produção: R${{ valortotal }} (energia)
                    </p>
                  </div>
                </label>
              </div>

              <div class="col-md">
                <br />
                <input type="radio" name="quadro" id="2" value="2" />
                <label for="2" class="l_quadro">
                  <div class="p-2 border bg-light quadros">
                    <h2 class="p-2">Quadro 2</h2>
                    <p class="text-left" style="margin-left: 20px">
                      Área de cada placa: {{ areaPlaca }}m²
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Área total do telhado: {{ areaTelhado }}m²
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Quantidade de placas que
                      <span style="font-weight: bold">são necessárias</span> ser
                      instaladas: {{ qtdPlacasNec }} placas
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Potência total em Watts: {{ potTotalNec }}W
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Potência total em Volts: {{ voltagemNec }}V
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Potência total em Amperes: {{ amperagemNec }}A
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Geração mensal: {{ geracaoMensalNec }}
                    </p>
                    <p class="text-left" style="margin-left: 20px">
                      Valor total de produção: R${{valortotalNec}} (energia)
                    </p>
                  </div>
                </label>
              </div>
            </div>

            <br /><br /><br />
            <a href="auth.send_data2"
              ><input
                type="submit"
                class="btn btn-lg"
                name=""
                value="Escolher"
              />
            </a>
          </form>
        </div>
      </div>

      <p class="text-center">O quadro escolhido foi o QUADRO {{ quadro }}.</p>
    </div>

    <div class="container p-3 text-center" id="secao3" style="display:{{ estadoTela3 }}">
      <form
        action="{{ url_for('auth.send_data3')  + '#secao4' }}"
        id="entrada-dados"
        action="{{ url_for('auth.send_data3') }}"
        method="post"
      >
        <h4>Dados do inversor</h4>
        <br />
        <!--Sistema deve solicitar ao usuário o modelo de inversor a ser utilizado com os seguintes dados:-->
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label for=""
                >Capacidade máxima em kw/h de injeção na rede elétrica:</label
              >
              <input
                type="text"
                class="form-control"
                name="altura-telhado"
                value=""
              />
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group">
              <label for="">Valor total do inversor:</label>
              <input
                type="text"
                class="form-control"
                name="comprimento-telhado"
                value=""
              />
            </div>
          </div>
        </div>

        <br /><br />

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <label for="">Capacidade máxima em Watts:</label>
              <input type="text" class="form-control" name="potInv" value="" />
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
              <label for="">Capacidade máxima em Volts:</label>
              <input
                type="text"
                class="form-control"
                name="voltagemInv"
                value=""
              />
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
              <label for="">Capacidade máxima em Amperes:</label>
              <input
                type="text"
                class="form-control"
                name="amperagemInv"
                value=""
              />
            </div>
          </div>
        </div>
        <br /><br />
        <a href="auth.send_data3"
          ><input
            type="submit"
            class="btn btn-lg"
            name=""
            value="Resultado final"
        /></a>
      </form>
    </div>

    <br /><br />
    <hr />
    <br /><br /><br />
    <div class="container p-3 text-center" style="display:{{ estadoTela4 }}">
      <div class="quadro_resultado" id="secao4">
        <br /><br />
        <h2>Dados de geração e de rendimento calculados</h2>
        <br /><br /><br />
        <h1>{{ nmenor }} inversor(es)</h1>
        <p class="text-center">
          Quantidade de inversores necessários para comportar a instalação com o
          modelo informado
        </p>

        <br /><br />

        <h1>{{ prodEletrica }}kWh</h1>
        <p class="text-center">
          Estimação da produção elétrica do sistema mensal e valor gerado por
          KW/H
        </p>

        <br /><br />

        <h1>R${{ taxa }}</h1>
        <p class="text-center">
          Dedução da taxa de utilização da rede da concessionária
        </p>

        <br /><br />

        <h1>{{ payback }} anos</h1>
        <p class="text-center">
          Quantidade de anos em que o investimento será pago
        </p>
      </div>
    </div>

    <br /><br /><br /><br />
  </body>
</html>

website/website/templates/home.html
{% extends "base.html" %}

website/website/templates/qdr.html
{% extends "base.html" %}

{% block qdr %}
    <p class="text-center">
        O quadro escolhido foi o QUADRO {{ quadro }}.</p>
    </p>
{% endblock %}

website/website/templates/sobre.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, inital-scale-1"/>
    <link rel="stylesheet" href="../static/css/master.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="icon" type="image/svg" href="../static/images/logotipo2.svg">
    <title>Simulador de capacidade de geração de energia solar</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm fixed-top">
     <div class="p-3 collapse navbar-collapse flex-row-reverse bg-warning" id="collapsibleNavbar" >
      <ul class="navbar-nav">
       <li class="nav-item">
        <a class="nav-link" href="/"><b>início</b></a>
       </li>
       <li class="nav-item">
        <a class="nav-link active" href="sobre.html">sobre</a>
       </li>
      </ul>
    </nav>

    <br><br><br><br>

    <div class="container p-5 text-center">
     <h1>Sobre o site</h1>
     <br><br>
     <h6>Atividade Avaliativa de Prática Profissional por Michelle Pani, do 3ºTI.</h6>
     <br>
     <h6>A princípio, a placa utilizada para os cálculos do website é a CANADIAN SOLAR - 455W - Modelo CS3W-455MS.</h6>
     <h6>Os valores referentes ao KW/H foram feitos levando em consideração a tarifa do estado do Rio de Janeiro (de acordo com o site <a href="https://brasil61.com/n/rio-de-janeiro-possui-a-maior-tarifa-media-de-energia-eletrica-entre-os-estados-da-regiao-sudeste-pind212980#:~:text=O%20Rio%20de%20Janeiro%20possui,%2Dhora%20(KWh)%20consumidos." class="fonte">Brasil61</a>).</h6>
    </div>

    <br><br><br>

    <div class="container p-5">
     <h1 class="text-center">Em breve</h1>
     <br><br>
     <ul class="embreve_ul">
      <li class="embreve_li"><span class="material-symbols-outlined">task_alt</span><h6>&nbsp &nbsp &nbsp Aprimoramento da estética do website (paleta de cores + página "Sobre")</h6></li>
      <li class="embreve_li"><span class="material-symbols-outlined">task_alt</span><h6>&nbsp &nbsp &nbsp Seleção + destaque de quadros com clique (+ validação de escolha)</h6></li>
      <li class="embreve_li"><span class="material-symbols-outlined">task_alt</span><h6>&nbsp &nbsp &nbsp Otimização da navegação/rotas website</h6></li>
      <li class="embreve_li"><span class="material-symbols-outlined">task_alt</span><h6>&nbsp &nbsp &nbsp Design e implementação da logo do website</h6></li>
      <li class="embreve_li"><span class="material-symbols-outlined">task_alt</span><h6>&nbsp &nbsp &nbsp Link de ancoragem com o botão "calcular"</h6></li>
      <br>
      <li class="embreve_li"><span class="material-symbols-outlined">radio_button_unchecked</span><h6>&nbsp &nbsp &nbsp Banco de dados para escolher a placa utilizada durante os cálculos</h6></li>
      <li class="embreve_li"><span class="material-symbols-outlined">radio_button_unchecked</span><h6>&nbsp &nbsp &nbsp Telas e avisos de erro</h6></li>
      <li class="embreve_li"><span class="material-symbols-outlined">radio_button_unchecked</span><h6>&nbsp &nbsp &nbsp Limitação do input do usuário apenas a números</h6></li>
      <li class="embreve_li"><span class="material-symbols-outlined">radio_button_unchecked</span><h6>&nbsp &nbsp &nbsp Placeholders no formulário com as unidades de medida</h6></li>
      <li class="embreve_li"><span class="material-symbols-outlined">radio_button_unchecked</span><h6>&nbsp &nbsp &nbsp Botão de "Calcular novamente"</h6></li>
      <li class="embreve_li"><span class="material-symbols-outlined">radio_button_unchecked</span><h6>&nbsp &nbsp &nbsp Atualização de placas disponíveis com web scrapping</h6></li>
     </ul>
    </div>

  </body>
  
</html>